version: "3.9"

name: todoApp

services:
  todo:
    build:
      context: ./todo
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000

  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=ziakhan
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - '5433:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "uzair330@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db

volumes:
  postgres_db:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    driver: bridge
